server:
  port: 8071

spring:
  application:
    name: configserver
  profiles:
    active: git
  #active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eazybytes/eazybytes-config.git
          default-label: main # git 어떤 브랜치인지 입력
          timeout: 5
          clone-on-start: true # git 에서 설정파일 clone 해옴
          force-pull: true # 변경사항이 있어도
#        native:
#          search-locations: file:///Users//uitae//Documents//config # Mac 에서 설정파일 불러오기
#          search-locations: classpath:/config # resources/config 내 설정파일 불러오기
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true