services:
  network-deploy-service:
    networks:
      - utlee

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
  #      SPRING_RABBITMQ_HOST: "rabbit"
      JAVA_TOOL_OPTIONS: "-javaagent:/app/libs/opentelemetry-javaagent-1.32.0.jar"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317
      OTEL_METRICS_EXPORTER: none

  microservice-configserver-config:
    extends:
      service: microservice-base-config
#    depends_on:
#      configserver:
#        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: "optional:configserver:http://configserver:8071/"
      SPRING_DATASOURCE_URL: "jdbc:mariadb://192.168.31.122:33066/webapp?characterEncoding=UTF-8"
      SPRING_DATASOURCE_USERNAME: utlee
      SPRING_DATASOURCE_PASSWORD: p@ssword1

  microservice-eureka-config:
    extends:
      service: microservice-configserver-config
#    depends_on:
#      eurekaserver:
#        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/